spring.application.name=Module2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/2001d/dkmeclipse/Module2DB
spring.datasource.username=dkm123
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update