package com.example.Modeule3.entities;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.CreationTimestamp;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity
@ToString
@Getter
@Setter
@Table(name = "patients")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Patient2 {
   
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	private String name;
	
	private LocalDate birthDate;
	
	private String email;
	
	private String gender;
	
	@Enumerated(value=EnumType.STRING)
	private BloodGroupType bloodGroup;
	
	@Column(updatable = false)
	@CreationTimestamp
	private LocalDateTime createdAt;
	
	@OneToOne(cascade= CascadeType.ALL, orphanRemoval=true)
	@JoinColumn(name="patient_insurnce", unique=true)//by default name is insurance_id field generated by hibernate
	private Insurance insurance;
	
	
	@OneToMany(mappedBy="patient", cascade=CascadeType.ALL,fetch=FetchType.EAGER)//inverse side
//	@ToString.Exclude
	private Set<Appointment>appointments=new HashSet<>();
}
