spring.application.name=Module3


spring.datasource.url=jdbc:mysql://localhost:3306/module3DB?useSSL=false
spring.datasource.username=root
spring.datasource.password=#pyG4XsLkN

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8085
#it seeds the db with some dummy data
spring.jpa.defer-datasource-initialization=true 

#`spring.sql.init.mode=always` forces Spring Boot to run `schema.sql` and `data.sql` on **every application startup**, for **all database types**.
spring.sql.init.mode=always

#seeded data comes from this locaion
spring.sql.init.data-locations=classpath:data.sql