spring.application.name=Module2HomeWork
spring.datasource.url=jdbc:h2:file:C:/Users/2001d/dkmeclipse/Module2HomeWorkDB
spring.datasource.username=dkm123
spring.datasource.password=password123
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
